{% set version = "0.17.1" %}

package:
  name: fermipy
  version: {{version}}

source:
  fn: fermipy-{{version}}.tar.gz
  url: https://pypi.io/packages/source/f/fermipy/fermipy-{{ version }}.tar.gz 
  md5: 751cc4ac9ac2231eb65652a0b7645732

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  skip: True  # [win]
  entry_points:
    - fermipy-dispatch = fermipy.scripts.dispatch:main
    - fermipy-clone-configs = fermipy.scripts.clone_configs:main
    - fermipy-collect-sources = fermipy.scripts.collect_sources:main
    - fermipy-cluster-sources = fermipy.scripts.cluster_sources:main
    - fermipy-flux-sensitivity = fermipy.scripts.flux_sensitivity:main
    - fermipy-intensity-map = fermipy.scripts.intensity_map:main
    - fermipy-run-tempo = fermipy.scripts.run_tempo:main
    - fermipy-healview = fermipy.scripts.HEALview:main
    - fermipy-select = fermipy.scripts.select_data:main
    - fermipy-preprocess = fermipy.scripts.preprocess_data:main
    - fermipy-astroserver = fermipy.scripts.astroserver:main
    - fermipy-validate = fermipy.scripts.validate:main
    - fermipy-merit-skimmer = fermipy.scripts.merit_skimmer:main
    - fermipy-merit-response = fermipy.scripts.merit_response:main
    - fermipy-quick-analysis = fermipy.scripts.quickanalysis:main
    - fermipy-coadd = fermipy.scripts.coadd:main
    - fermipy-vstack = fermipy.scripts.vstack_images:main
    - fermipy-gtexcube2-sg = fermipy.diffuse.job_library:invoke_sg_gtexpcube2
    - fermipy-sum-ring-gasmaps-sg = fermipy.diffuse.job_library:invoke_sg_sum_ring_gasmaps
    - fermipy-vstack-diffuse-sg = fermipy.diffuse.job_library:invoke_sg_vstack_diffuse
    - fermipy-healview-diffuse-sg = fermipy.diffuse.job_library:invoke_sg_healview_diffuse
    - fermipy-srcmaps-catalog-sg = fermipy.diffuse.job_library:invoke_sg_gtsrcmaps_catalog
    - fermipy-split-and-bin = fermipy.diffuse.gt_split_and_bin:main_single
    - fermipy-split-and-bin-sg = fermipy.diffuse.gt_split_and_bin:main_batch
    - fermipy-split-and-mktime = fermipy.diffuse.gt_split_and_mktime:main_single
    - fermipy-split-and-mktime-sg = fermipy.diffuse.gt_split_and_mktime:main_batch
    - fermipy-coadd-split = fermipy.diffuse.gt_coadd_split:main
    - fermipy-srcmaps-diffuse = fermipy.diffuse.gt_srcmap_partial:main_single
    - fermipy-srcmaps-diffuse-sg = fermipy.diffuse.gt_srcmap_partial:main_batch
    - fermipy-merge-srcmaps = fermipy.diffuse.gt_merge_srcmaps:main_single
    - fermipy-merge-srcmaps-sg = fermipy.diffuse.gt_merge_srcmaps:main_batch
    - fermipy-init-model = fermipy.diffuse.gt_assemble_model:main_init
    - fermipy-assemble-model = fermipy.diffuse.gt_assemble_model:main_single
    - fermipy-assemble-model-sg = fermipy.diffuse.gt_assemble_model:main_batch
    - fermipy-residual-cr = fermipy.diffuse.residual_cr:main_single
    - fermipy-residual-cr-sg = fermipy.diffuse.residual_cr:main_batch
    - fermipy-residual-cr-chain = fermipy.diffuse.residual_cr:main_chain
    - fermipy-catalog-chain = fermipy.diffuse.catalog_src_manager:main_chain
    - fermipy-diffuse-chain = fermipy.diffuse.diffuse_src_manager:main_chain
    - fermipy-diffuse-analysis = fermipy.diffuse.diffuse_analysis:main_chain
    - fermipy-gtexphpsun-sg = fermipy.diffuse.solar:invoke_sg_Gtexphpsun
    - fermipy-gtsuntemp-sg = fermipy.diffuse.solar:invoke_sg_Gtsuntemp
    - fermipy-sunmoon = fermipy.diffuse.solar:main
    - fermipy-job-archive = fermipy.jobs.job_archive:main_browse
    - fermipy-file-archive = fermipy.jobs.file_archive:main_browse
    
requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy >=1.6.1
    - astropy >=1.2.1
    - matplotlib >=1.5.0
    - scipy >=0.14
    - pyyaml
    - healpy
    - wcsaxes

test:
  imports:
    - fermipy

about:
  home: https://github.com/fermiPy/fermipy
  license:  BSD 3-Clause
  summary: "Fermipy is a python package for analysis of Fermi-LAT data"
  license_file: LICENSE.rst
  doc_url: http://fermipy.readthedocs.io
  dev_url: https://github.com/fermiPy/fermipy

extra:
  recipe-maintainers:
    - woodmd
